name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Hugo
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.92.2'  # You can specify the version of Hugo you're using

    # Build the Hugo site
    - name: Build Hugo site
      run: hugo --minify

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Branch where the site will be deployed
        folder: public    # The folder containing the built site (default is "public" for Hugo)
        token: ${{ secrets.GITHUB_TOKEN }}
